name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test --coverage
      - uses: codecov/codecov-action@v1

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - name: Build
        run: yarn build
      - name: Deploy
        uses: peaceiris/actions-github-pages@v3.1.12
        with:
          publish_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
